#!/usr/bin/env python3
"""Interactive Ubuntu deployment. Uses standard library only."""
from __future__ import annotations

import getpass
import http.cookiejar
import ipaddress
import json
import os
from pathlib import Path
import re
import secrets
import shutil
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

ROOT = Path(__file__).resolve().parent.parent
MARKER = "# Generated by Monitoring Local installer.\n"
CATALOG = json.loads((ROOT / "public" / "equipment.json").read_text(encoding="utf-8"))
PROTOCOLS = {item["id"]: (item["label"], item["port"], item["transport"]) for item in CATALOG["protocols"]}

COMPOSE = ["docker", "compose"]
# Explicitly bypass proxy environment variables for local admin credentials.
HTTP = urllib.request.build_opener(urllib.request.ProxyHandler({}),
    urllib.request.HTTPCookieProcessor(http.cookiejar.CookieJar()))


def run(args, capture=False):
    return subprocess.run(args, cwd=ROOT, check=True, text=True,
                          stdout=subprocess.PIPE if capture else None).stdout


def atomic_write(path, text, mode=0o600):
    path = Path(path)
    if path.is_symlink():
        raise ValueError(f"Отказ от перезаписи символической ссылки: {path}")
    temporary = path.with_name(path.name + ".tmp-" + secrets.token_hex(6))
    fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL, mode)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(text)
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def ensure_env(root):
    target = root / ".env"
    if target.exists():
        text = target.read_text(encoding="utf-8")
        entries = dict(line.split("=", 1) for line in text.splitlines()
                       if "=" in line and not line.lstrip().startswith("#"))
        if not entries.get("POSTGRES_PASSWORD", "").strip().strip("'\""):
            raise ValueError("В существующем .env пустой POSTGRES_PASSWORD. Укажите пароль существующей БД; мастер не заменяет его.")
        return False
    content = (root / ".env.example").read_text(encoding="utf-8")
    content = re.sub(r"(?m)^POSTGRES_PASSWORD=.*$", "POSTGRES_PASSWORD=" + secrets.token_hex(32), content)
    atomic_write(target, content)
    return True


def validate_host(value):
    value = value.strip().lower().rstrip(".")
    try:
        address = ipaddress.IPv4Address(value)
        if address.is_unspecified or address.is_multicast or address.is_loopback:
            raise ValueError("Нужен достижимый IPv4-адрес, не 0.0.0.0 или loopback.")
        return str(address)
    except ipaddress.AddressValueError:
        pass
    labels = value.split(".")
    if len(value) > 253 or len(labels) < 2 or all(label.isdigit() for label in labels):
        raise ValueError("Укажите IPv4 или полное DNS-имя без http://, пути и порта.")
    if not all(re.fullmatch(r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?", label) for label in labels):
        raise ValueError("Некорректное DNS-имя. Для международных имён используйте punycode.")
    return value


def validate_plan(plan, local_ips):
    if plan["bind"] not in local_ips:
        raise ValueError("Выбранный IP должен быть назначен интерфейсу этого сервера.")
    address = ipaddress.IPv4Address(plan["bind"])
    if address.is_loopback or address.is_multicast or address.is_unspecified:
        raise ValueError("Для локального доступа выберите адрес сетевого интерфейса.")
    if type(plan["web_port"]) is not int or not 1024 <= plan["web_port"] <= 65535:
        raise ValueError("Порт сайта должен быть от 1024 до 65535.")
    if not plan["protocols"] or len(set(plan["protocols"])) != len(plan["protocols"]):
        raise ValueError("Выберите хотя бы один протокол без повторений.")
    if any(key not in PROTOCOLS for key in plan["protocols"]):
        raise ValueError("Неизвестный протокол.")
    reserved = {8082} | {PROTOCOLS[key][1] for key in plan["protocols"]}
    if plan["web_port"] in reserved:
        raise ValueError("Порт сайта пересекается с API или выбранным протоколом.")
    if plan.get("external"):
        plan["external"] = validate_host(plan["external"])
    return plan


def render_override(plan, bootstrap=False):
    bind = "127.0.0.1" if bootstrap else plan["bind"]
    # !override prevents Compose from ADDING ports to old/default bindings.
    text = MARKER + "services:\n  web:\n    ports: !override\n"
    text += f'      - "{bind}:{plan["web_port"]}:80/tcp"\n'
    text += '    volumes:\n      - "./.local/connection.json:/usr/share/nginx/html/connection.json:ro"\n'
    text += "  traccar:\n    ports: !override\n      - \"127.0.0.1:8082:8082/tcp\"\n"
    for key in plan["protocols"]:
        _, port, transport = PROTOCOLS[key]
        text += f'      - "{bind}:{port}:{port}/{transport}"\n'
    text += "    environment:\n"
    for key in plan["protocols"]:
        text += f'      {key.upper()}_PORT: "{PROTOCOLS[key][1]}"\n'
    return text


def write_override(root, plan, bootstrap=False):
    target = root / "compose.override.yaml"
    if target.exists() and not target.read_text(encoding="utf-8").startswith(MARKER):
        raise ValueError("Найден ваш compose.override.yaml. Мастер не перезаписывает чужие настройки; перенесите их вручную.")
    local = root / ".local"
    local.mkdir(exist_ok=True)
    atomic_write(local / "connection.json", json.dumps({
        "configured": not bootstrap, "host": plan.get("external") or "",
        "localHost": plan["bind"], "protocols": plan["protocols"],
    }, ensure_ascii=False), mode=0o644)
    atomic_write(target, render_override(plan, bootstrap))


def local_addresses():
    data = json.loads(run(["ip", "-j", "-4", "addr", "show", "scope", "global"], capture=True))
    return list(dict.fromkeys(info["local"] for link in data
        if not link["ifname"].startswith(("docker", "br-", "veth"))
        for info in link.get("addr_info", []) if info["family"] == "inet"))


def ask(label, default=""):
    suffix = f" [{default}]" if default else ""
    return input(label + suffix + ": ").strip() or str(default)


def collect_plan(addresses, previous):
    print("\nСетевые адреса сервера: " + ", ".join(addresses))
    print("Выберите постоянный адрес LAN. Сайт останется на HTTP внутри вашей сети.")
    while True:
        try:
            bind = ask("IP сервера в локальной сети", previous.get("bind", addresses[0]))
            web_port = int(ask("Порт сайта", previous.get("web_port", 8080)))
            print("\nПротоколы (выбор зависит от точной модели и настроек терминала):")
            for index, (key, (label, port, transport)) in enumerate(PROTOCOLS.items(), 1):
                print(f"  {index}. {label}: {port}/{transport}")
            defaults = ",".join(str(list(PROTOCOLS).index(key) + 1)
                for key in previous.get("protocols", ["osmand"]) if key in PROTOCOLS)
            selection = ask("Номера через запятую", defaults or "1")
            indexes = [int(part.strip()) for part in selection.split(",")]
            if any(index < 1 or index > len(PROTOCOLS) for index in indexes):
                raise ValueError("Номер протокола вне списка.")
            protocols = [list(PROTOCOLS)[index - 1] for index in indexes]
            external = ask("Внешний IP/DNS для терминалов (Enter — только LAN, '-' — очистить)",
                           previous.get("external", ""))
            if external == "-":
                external = ""
            return validate_plan(dict(bind=bind, web_port=web_port,
                protocols=protocols, external=external), addresses)
        except ValueError as error:
            print("Проверьте ввод:", error)


def package_installed(name):
    result = subprocess.run(["dpkg-query", "-W", "-f=${Status}", name],
                            capture_output=True, text=True)
    return result.returncode == 0 and result.stdout == "install ok installed"


def setup_docker_repo():
    sources = [Path("/etc/apt/sources.list")]
    sources += list(Path("/etc/apt/sources.list.d").glob("*.list"))
    sources += list(Path("/etc/apt/sources.list.d").glob("*.sources"))
    if any(path.exists() and "download.docker.com/linux/ubuntu" in path.read_text()
           for path in sources):
        return
    release = dict(line.split("=", 1) for line in Path("/etc/os-release").read_text().splitlines() if "=" in line)
    codename = release.get("VERSION_CODENAME", "").strip('"')
    if codename not in ("jammy", "noble", "resolute"):
        raise ValueError("Неподдерживаемая версия Ubuntu для репозитория Docker.")
    architecture = run(["dpkg", "--print-architecture"], capture=True).strip()
    Path("/etc/apt/keyrings").mkdir(mode=0o755, exist_ok=True)
    # Download as data; never execute a fetched shell script.
    key = Path("/etc/apt/keyrings/monitoring-docker.asc")
    run(["curl", "--fail", "--show-error", "--silent", "--location",
         "--connect-timeout", "20", "--max-time", "120",
         "https://download.docker.com/linux/ubuntu/gpg", "-o", str(key)])
    key.chmod(0o644)
    atomic_write(Path("/etc/apt/sources.list.d/monitoring-docker.sources"),
        "Types: deb\nURIs: https://download.docker.com/linux/ubuntu\n"
        f"Suites: {codename}\nComponents: stable\nArchitectures: {architecture}\n"
        "Signed-By: /etc/apt/keyrings/monitoring-docker.asc\n", 0o644)


def ensure_docker():
    packages = []
    if not shutil.which("docker"):
        conflicts = [name for name in ("docker.io", "docker-compose", "docker-compose-v2",
            "podman-docker", "containerd", "runc") if package_installed(name)]
        if conflicts:
            raise ValueError("Найдены существующие контейнерные пакеты: " + ", ".join(conflicts)
                + ". Автоматическая замена может затронуть другие сервисы. Установите совместимый Docker Engine отдельно.")
        setup_docker_repo()
        packages = ["docker-ce", "docker-ce-cli", "containerd.io",
                    "docker-buildx-plugin", "docker-compose-plugin"]
    else:
        compose_ok = subprocess.run(COMPOSE + ["version"], capture_output=True).returncode == 0
        buildx_ok = subprocess.run(["docker", "buildx", "version"], capture_output=True).returncode == 0
        if not (compose_ok and buildx_ok):
            if package_installed("docker-ce"):
                setup_docker_repo()
                packages = ([] if compose_ok else ["docker-compose-plugin"]) + ([] if buildx_ok else ["docker-buildx-plugin"])
            elif package_installed("docker.io"):
                packages = ([] if compose_ok else ["docker-compose-v2"]) + ([] if buildx_ok else ["docker-buildx"])
            else:
                raise ValueError("Docker установлен нестандартно. Добавьте Compose v2 и Buildx для этой установки.")
    if packages:
        run(["apt-get", "update"])
        run(["apt-get", "install", "-y", "--no-install-recommends"] + packages)
    run(["systemctl", "enable", "--now", "docker"])
    run(["docker", "info"], capture=True)
    version = run(COMPOSE + ["version", "--short"], capture=True).strip()
    numbers = re.search(r"(\d+)\.(\d+)\.(\d+)", version)
    if not numbers or tuple(map(int, numbers.groups())) < (2, 24, 4):
        raise ValueError("Нужен Docker Compose >= 2.24.4 (поддержка !override). Обновите Compose.")
    # Avoid silently targeting a remote Docker host.
    context = json.loads(run(["docker", "context", "inspect"], capture=True))[0]
    endpoint = context.get("Endpoints", {}).get("docker", {}).get("Host", "")
    if not endpoint.startswith("unix://") or os.environ.get("DOCKER_HOST"):
        raise ValueError("Мастер работает только с локальным Docker через unix socket.")


def api(path, body=None, form=False, method=None):
    headers = {"Accept": "application/json"}
    data = None
    if body is not None:
        headers["Content-Type"] = "application/x-www-form-urlencoded" if form else "application/json"
        data = (urllib.parse.urlencode(body) if form else json.dumps(body)).encode()
    request = urllib.request.Request("http://127.0.0.1:8082/api" + path,
                                     data=data, headers=headers, method=method)
    with HTTP.open(request, timeout=20) as response:
        result = response.read()
        return json.loads(result) if result else None


def bootstrap_admin():
    server = api("/server")
    if not server["newServer"]:
        print("Учётные записи уже существуют. Пароли и пользователи оставлены без изменений.")
        if server.get("registration"):
            raise ValueError("В существующей системе включена регистрация. Отключите её через штатный интерфейс перед открытием LAN.")
        return "Существующая учётная запись администратора"
    print("\nСоздание первого администратора (пароль не будет записан в файлы):")
    name = ask("Имя администратора", "Администратор")
    while True:
        email = ask("Email для входа")
        if re.fullmatch(r"[^\s@]+@[^\s@]+\.[^\s@]+", email):
            break
        print("Введите корректный email.")
    while True:
        password = getpass.getpass("Пароль (не менее 12 символов): ")
        if len(password) < 12:
            print("Пароль слишком короткий.")
            continue
        if password == getpass.getpass("Повторите пароль: "):
            break
        print("Пароли не совпали.")
    api("/users", {"name": name, "email": email, "password": password})
    session = api("/session", {"email": email, "password": password}, form=True)
    if not session.get("administrator"):
        raise ValueError("Созданная учётная запись не администратор. LAN не открыт.")
    server = api("/server")
    if server.get("registration"):
        server["registration"] = False
        api("/server", server, method="PUT")
    if api("/server").get("registration"):
        raise ValueError("Не удалось отключить открытую регистрацию.")
    api("/session", method="DELETE")
    return email


def summary(plan, admin):
    website = f'http://{plan["bind"]}:{plan["web_port"]}'
    lines = ["ИнТехТранспорт — установка завершена", "",
             "Сайт (локальная сеть): " + website,
             "После входа: Мониторинг / Менеджер",
             "Администратор: " + admin, "",
             "Терминалы в локальной сети:"]
    for key in plan["protocols"]:
        label, port, transport = PROTOCOLS[key]
        lines.append(f"  {label}: адрес {plan['bind']}, порт {port}, транспорт {transport.upper()}")
    external = plan.get("external")
    if external:
        lines += ["", "Заданный внешний адрес: " + external,
                  "Это настройка, а не подтверждение доступности из интернета."]
        try:
            ipaddress.IPv4Address(external)
        except ipaddress.AddressValueError:
            try:
                ips = sorted({entry[4][0] for entry in socket.getaddrinfo(external, None, socket.AF_INET)})
                lines.append("Текущие DNS A-адреса: " + ", ".join(ips))
            except socket.gaierror:
                lines.append("DNS пока не разрешается. Создайте A-запись этого имени на публичный IPv4 вашего подключения.")
        for key in plan["protocols"]:
            label, port, transport = PROTOCOLS[key]
            lines.append(f"  {label}: {external}:{port} / {transport.upper()}")
            lines.append(f"  При NAT: внешний {port}/{transport} → {plan['bind']}:{port}/{transport}")
        lines.append("DNS не пробрасывает порты. При CGNAT нужен публичный IP либо VPN/частный APN.")
    else:
        lines += ["", "Внешний адрес не задан. Терминалы вне LAN подключатся только после настройки публичного адреса или VPN."]
    lines += ["", "В каждом трекере: APN оператора + адрес выше + порт своего протокола.",
              "IMEI/ID добавьте в разделе «Мониторинг»; клиенту назначьте транспорт в «Менеджере».",
              "Выбран TCP: настройте терминалы на TCP. Другие модели и UDP настраиваются отдельно.",
              "Docker-порты могут обходить UFW. Проверьте доступ на маршрутизаторе/в DOCKER-USER.",
              "Сайт работает по HTTP для доверенной LAN. Не публикуйте его в интернет без HTTPS.",
              "", "Проверка: sudo bash scripts/check.sh", "Резервная копия: sudo bash scripts/backup.sh",
              "Повторный запуск: bash install.sh", "Служебный Traccar: 127.0.0.1:8082 (SSH-туннель)."]
    return "\n".join(lines) + "\n"


def check_ports(plan):
    endpoints = [(plan["bind"], plan["web_port"]), ("127.0.0.1", plan["web_port"]),
                 ("127.0.0.1", 8082)]
    for key in plan["protocols"]:
        port = PROTOCOLS[key][1]
        endpoints += [(plan["bind"], port), ("127.0.0.1", port)]
    # Existing project containers own their ports on repeat runs; Compose performs final check.
    if run(COMPOSE + ["ps", "-q"], capture=True).strip():
        print("Найдены контейнеры проекта: занятость их портов проверит Docker при пересоздании.")
        return
    for address, port in set(endpoints):
        with socket.socket() as probe:
            try:
                probe.bind((address, port))
            except OSError as error:
                raise ValueError(f"Недоступен порт {address}:{port}: {error}") from error


def main():
    if sys.platform != "linux" or os.geteuid() != 0:
        raise ValueError("Запускайте на Ubuntu через bash install.sh (нужен sudo).")
    os.umask(0o077)
    if not sys.stdin.isatty():
        raise ValueError("Нужен интерактивный терминал. Запустите bash install.sh через SSH.")
    # Prevent two installers from changing configuration simultaneously.
    import fcntl
    local = ROOT / ".local"
    local.mkdir(mode=0o700, exist_ok=True)
    with (local / "install.lock").open("w") as lock:
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError as error:
            raise ValueError("Другой мастер установки уже запущен.") from error
        state = local / "install-state.json"
        previous = json.loads(state.read_text()) if state.exists() else {}
        target = ROOT / "compose.override.yaml"
        if target.exists() and not target.read_text().startswith(MARKER):
            raise ValueError("Найден пользовательский compose.override.yaml. Его нужно согласовать с мастером вручную.")
        addresses = local_addresses()
        if not addresses:
            raise ValueError("Не найден IPv4 сетевого интерфейса. Сначала настройте сеть сервера.")
        free_gb = shutil.disk_usage(ROOT).free / 1024**3
        print(f"\nИнТехТранспорт — мастер установки\nСвободно на диске проекта: {free_gb:.1f} ГБ")
        if free_gb < 5:
            raise ValueError("Для установки требуется не менее 5 ГБ свободного места; под историю понадобится больше.")
        plan = collect_plan(addresses, previous)
        print("\nБудет установлен Docker/Compose при необходимости, скачаны образы и собран сайт.")
        print(f"Сайт: http://{plan['bind']}:{plan['web_port']}; протоколы: " + ", ".join(plan["protocols"]))
        print("При повторной установке сервисы кратковременно станут недоступны в LAN. База и пароли сохранятся.")
        if ask("Начать установку? да/нет", "да").lower() not in ("да", "д", "yes", "y"):
            print("Отменено.")
            return
        ensure_docker()
        ensure_env(ROOT)
        if target.exists():
            atomic_write(local / ("compose-previous-" + str(time.time_ns()) + ".yaml"), target.read_text())
        atomic_write(state, json.dumps(plan, ensure_ascii=False, indent=2))
        write_override(ROOT, plan, bootstrap=True)
        run(COMPOSE + ["config", "--quiet"])
        check_ports(plan)
        print("\nСкачивание образов и сборка. Первый запуск может занять несколько минут…")
        run(COMPOSE + ["up", "-d", "--build", "--wait", "--wait-timeout", "600"])
        admin = bootstrap_admin()
        write_override(ROOT, plan, bootstrap=False)
        run(COMPOSE + ["up", "-d", "--force-recreate", "--wait", "--wait-timeout", "300", "traccar", "web"])
        with HTTP.open(f'http://{plan["bind"]}:{plan["web_port"]}/api/server', timeout=20) as response:
            if response.status != 200:
                raise ValueError("Сайт не прошёл итоговую проверку.")
        report = summary(plan, admin)
        atomic_write(local / "installation.txt", report)
        print("\n" + report)
        print("Памятка сохранена: " + str(local / "installation.txt"))


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print("\nМастер прерван. Данные сохранены. Повторите bash install.sh.", file=sys.stderr)
        sys.exit(1)
    except (ValueError, OSError, subprocess.CalledProcessError, urllib.error.URLError) as error:
        print("\nУстановка не завершена: " + str(error), file=sys.stderr)
        print("Данные не удалены. Проверьте sudo docker compose ps и logs --tail 100. Затем повторите bash install.sh.", file=sys.stderr)
        sys.exit(1)
